env:

replicaCount: 1

ingress:
  host: ibank-web.apps.devocp.firstbank.com.tw
  path: /c1/ileobank

image:
  repository: devharbor.firstbank.com.tw/ibank-web/ileobank
  tag: 0.0.6
  pull:
    secret: harbor-secret
    policy: Always

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 18000
  # targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: 10m
    memory: 20M
  limits:
    cpu: 2
    memory: 1.5G

tls:
  secretName: api-tls-certificates

configurationFiles:
  bitnami-nginx-server-blocks.conf: |-
    server {
        listen       8081;
        listen  [::]:8081;
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;

        index index.html ;
        location /c1/ileobank/en {
            alias   /web/en/;
            try_files $uri$args $uri$args/ /en/index.html;
        }

        location /c1/ileobank/zh {
            alias   /web/zh/;
            try_files $uri$args $uri$args/ /zh/index.html;
        }

        location /c1/ileobank {
            alias   /web/zh/;
            try_files $uri$args $uri$args/ /index.html;
        }
    }
